'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.832
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.832.
'
Namespace aFinder
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="WebServicesSoap", [Namespace]:="http://www.afinder.com.br")>  _
    Partial Public Class WebServices
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private authHeaderValueField As AuthHeader
        
        Private BuscaFoneticaXmlOperationCompleted As System.Threading.SendOrPostCallback
        
        Private BuscaXmlOperationCompleted As System.Threading.SendOrPostCallback
        
        Private BuscaProximidadesXmlOperationCompleted As System.Threading.SendOrPostCallback
        
        Private BuscaCPFXmlOperationCompleted As System.Threading.SendOrPostCallback
        
        Private BuscaAutXmlOperationCompleted As System.Threading.SendOrPostCallback
        
        Private BuscaParentesXmlOperationCompleted As System.Threading.SendOrPostCallback
        
        Private BuscaCEPXmlOperationCompleted As System.Threading.SendOrPostCallback
        
        Private HigienizarXmlOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://www.afinder.com.br/afinderx/WebServiceS.asmx"
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Property AuthHeaderValue() As AuthHeader
            Get
                Return Me.authHeaderValueField
            End Get
            Set
                Me.authHeaderValueField = value
            End Set
        End Property
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event BuscaFoneticaXmlCompleted As BuscaFoneticaXmlCompletedEventHandler
        
        '''<remarks/>
        Public Event BuscaXmlCompleted As BuscaXmlCompletedEventHandler
        
        '''<remarks/>
        Public Event BuscaProximidadesXmlCompleted As BuscaProximidadesXmlCompletedEventHandler
        
        '''<remarks/>
        Public Event BuscaCPFXmlCompleted As BuscaCPFXmlCompletedEventHandler
        
        '''<remarks/>
        Public Event BuscaAutXmlCompleted As BuscaAutXmlCompletedEventHandler
        
        '''<remarks/>
        Public Event BuscaParentesXmlCompleted As BuscaParentesXmlCompletedEventHandler
        
        '''<remarks/>
        Public Event BuscaCEPXmlCompleted As BuscaCEPXmlCompletedEventHandler
        
        '''<remarks/>
        Public Event HigienizarXmlCompleted As HigienizarXmlCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.afinder.com.br/BuscaFoneticaXml", RequestNamespace:="http://www.afinder.com.br", ResponseNamespace:="http://www.afinder.com.br", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function BuscaFoneticaXml(ByVal Busca As String, ByVal Fonetica As String, ByVal Direcao As Integer, ByVal UF As String, ByVal Cidade As String, ByVal Bairro As String, ByVal Endereco As String, ByVal Numero As String, ByVal Complemento As String, ByVal Nome As String, ByVal Bases As String) As System.Xml.XmlNode
            Dim results() As Object = Me.Invoke("BuscaFoneticaXml", New Object() {Busca, Fonetica, Direcao, UF, Cidade, Bairro, Endereco, Numero, Complemento, Nome, Bases})
            Return CType(results(0),System.Xml.XmlNode)
        End Function
        
        '''<remarks/>
        Public Overloads Sub BuscaFoneticaXmlAsync(ByVal Busca As String, ByVal Fonetica As String, ByVal Direcao As Integer, ByVal UF As String, ByVal Cidade As String, ByVal Bairro As String, ByVal Endereco As String, ByVal Numero As String, ByVal Complemento As String, ByVal Nome As String, ByVal Bases As String)
            Me.BuscaFoneticaXmlAsync(Busca, Fonetica, Direcao, UF, Cidade, Bairro, Endereco, Numero, Complemento, Nome, Bases, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub BuscaFoneticaXmlAsync(ByVal Busca As String, ByVal Fonetica As String, ByVal Direcao As Integer, ByVal UF As String, ByVal Cidade As String, ByVal Bairro As String, ByVal Endereco As String, ByVal Numero As String, ByVal Complemento As String, ByVal Nome As String, ByVal Bases As String, ByVal userState As Object)
            If (Me.BuscaFoneticaXmlOperationCompleted Is Nothing) Then
                Me.BuscaFoneticaXmlOperationCompleted = AddressOf Me.OnBuscaFoneticaXmlOperationCompleted
            End If
            Me.InvokeAsync("BuscaFoneticaXml", New Object() {Busca, Fonetica, Direcao, UF, Cidade, Bairro, Endereco, Numero, Complemento, Nome, Bases}, Me.BuscaFoneticaXmlOperationCompleted, userState)
        End Sub
        
        Private Sub OnBuscaFoneticaXmlOperationCompleted(ByVal arg As Object)
            If (Not (Me.BuscaFoneticaXmlCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent BuscaFoneticaXmlCompleted(Me, New BuscaFoneticaXmlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.afinder.com.br/BuscaXml", RequestNamespace:="http://www.afinder.com.br", ResponseNamespace:="http://www.afinder.com.br", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function BuscaXml(ByVal UF As String, ByVal Cidade As String, ByVal Bairro As String, ByVal Endereco As String, ByVal Numero As String, ByVal Complemento As String, ByVal CEP As String, ByVal Nome As String, ByVal CPF As String, ByVal DDD As String, ByVal Fone As String, ByVal Registros As Integer, ByVal Bases As String) As System.Xml.XmlNode
            Dim results() As Object = Me.Invoke("BuscaXml", New Object() {UF, Cidade, Bairro, Endereco, Numero, Complemento, CEP, Nome, CPF, DDD, Fone, Registros, Bases})
            Return CType(results(0),System.Xml.XmlNode)
        End Function
        
        '''<remarks/>
        Public Overloads Sub BuscaXmlAsync(ByVal UF As String, ByVal Cidade As String, ByVal Bairro As String, ByVal Endereco As String, ByVal Numero As String, ByVal Complemento As String, ByVal CEP As String, ByVal Nome As String, ByVal CPF As String, ByVal DDD As String, ByVal Fone As String, ByVal Registros As Integer, ByVal Bases As String)
            Me.BuscaXmlAsync(UF, Cidade, Bairro, Endereco, Numero, Complemento, CEP, Nome, CPF, DDD, Fone, Registros, Bases, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub BuscaXmlAsync(ByVal UF As String, ByVal Cidade As String, ByVal Bairro As String, ByVal Endereco As String, ByVal Numero As String, ByVal Complemento As String, ByVal CEP As String, ByVal Nome As String, ByVal CPF As String, ByVal DDD As String, ByVal Fone As String, ByVal Registros As Integer, ByVal Bases As String, ByVal userState As Object)
            If (Me.BuscaXmlOperationCompleted Is Nothing) Then
                Me.BuscaXmlOperationCompleted = AddressOf Me.OnBuscaXmlOperationCompleted
            End If
            Me.InvokeAsync("BuscaXml", New Object() {UF, Cidade, Bairro, Endereco, Numero, Complemento, CEP, Nome, CPF, DDD, Fone, Registros, Bases}, Me.BuscaXmlOperationCompleted, userState)
        End Sub
        
        Private Sub OnBuscaXmlOperationCompleted(ByVal arg As Object)
            If (Not (Me.BuscaXmlCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent BuscaXmlCompleted(Me, New BuscaXmlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.afinder.com.br/BuscaProximidadesXml", RequestNamespace:="http://www.afinder.com.br", ResponseNamespace:="http://www.afinder.com.br", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function BuscaProximidadesXml(ByVal UF As String, ByVal Cidade As String, ByVal Bairro As String, ByVal Endereco As String, ByVal Numero As String, ByVal Complemento As String, ByVal CEP As String, ByVal Registros As Integer, ByVal SentidoProximidade As Integer) As System.Xml.XmlNode
            Dim results() As Object = Me.Invoke("BuscaProximidadesXml", New Object() {UF, Cidade, Bairro, Endereco, Numero, Complemento, CEP, Registros, SentidoProximidade})
            Return CType(results(0),System.Xml.XmlNode)
        End Function
        
        '''<remarks/>
        Public Overloads Sub BuscaProximidadesXmlAsync(ByVal UF As String, ByVal Cidade As String, ByVal Bairro As String, ByVal Endereco As String, ByVal Numero As String, ByVal Complemento As String, ByVal CEP As String, ByVal Registros As Integer, ByVal SentidoProximidade As Integer)
            Me.BuscaProximidadesXmlAsync(UF, Cidade, Bairro, Endereco, Numero, Complemento, CEP, Registros, SentidoProximidade, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub BuscaProximidadesXmlAsync(ByVal UF As String, ByVal Cidade As String, ByVal Bairro As String, ByVal Endereco As String, ByVal Numero As String, ByVal Complemento As String, ByVal CEP As String, ByVal Registros As Integer, ByVal SentidoProximidade As Integer, ByVal userState As Object)
            If (Me.BuscaProximidadesXmlOperationCompleted Is Nothing) Then
                Me.BuscaProximidadesXmlOperationCompleted = AddressOf Me.OnBuscaProximidadesXmlOperationCompleted
            End If
            Me.InvokeAsync("BuscaProximidadesXml", New Object() {UF, Cidade, Bairro, Endereco, Numero, Complemento, CEP, Registros, SentidoProximidade}, Me.BuscaProximidadesXmlOperationCompleted, userState)
        End Sub
        
        Private Sub OnBuscaProximidadesXmlOperationCompleted(ByVal arg As Object)
            If (Not (Me.BuscaProximidadesXmlCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent BuscaProximidadesXmlCompleted(Me, New BuscaProximidadesXmlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.afinder.com.br/BuscaCPFXml", RequestNamespace:="http://www.afinder.com.br", ResponseNamespace:="http://www.afinder.com.br", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function BuscaCPFXml(ByVal UF As String, ByVal CPF As String, ByVal Registros As Integer, ByVal Bases As String) As System.Xml.XmlNode
            Dim results() As Object = Me.Invoke("BuscaCPFXml", New Object() {UF, CPF, Registros, Bases})
            Return CType(results(0),System.Xml.XmlNode)
        End Function
        
        '''<remarks/>
        Public Overloads Sub BuscaCPFXmlAsync(ByVal UF As String, ByVal CPF As String, ByVal Registros As Integer, ByVal Bases As String)
            Me.BuscaCPFXmlAsync(UF, CPF, Registros, Bases, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub BuscaCPFXmlAsync(ByVal UF As String, ByVal CPF As String, ByVal Registros As Integer, ByVal Bases As String, ByVal userState As Object)
            If (Me.BuscaCPFXmlOperationCompleted Is Nothing) Then
                Me.BuscaCPFXmlOperationCompleted = AddressOf Me.OnBuscaCPFXmlOperationCompleted
            End If
            Me.InvokeAsync("BuscaCPFXml", New Object() {UF, CPF, Registros, Bases}, Me.BuscaCPFXmlOperationCompleted, userState)
        End Sub
        
        Private Sub OnBuscaCPFXmlOperationCompleted(ByVal arg As Object)
            If (Not (Me.BuscaCPFXmlCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent BuscaCPFXmlCompleted(Me, New BuscaCPFXmlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.afinder.com.br/BuscaAutXml", RequestNamespace:="http://www.afinder.com.br", ResponseNamespace:="http://www.afinder.com.br", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function BuscaAutXml(ByVal UF As String, ByVal Cidade As String, ByVal Bairro As String, ByVal Endereco As String, ByVal Numero As String, ByVal Complemento As String, ByVal CEP As String, ByVal Nome As String, ByVal CPF As String, ByVal DDD As String, ByVal Fone As String, ByVal Registros As Integer, ByVal Higienizar As Boolean, ByVal Bases As String) As System.Xml.XmlNode
            Dim results() As Object = Me.Invoke("BuscaAutXml", New Object() {UF, Cidade, Bairro, Endereco, Numero, Complemento, CEP, Nome, CPF, DDD, Fone, Registros, Higienizar, Bases})
            Return CType(results(0),System.Xml.XmlNode)
        End Function
        
        '''<remarks/>
        Public Overloads Sub BuscaAutXmlAsync(ByVal UF As String, ByVal Cidade As String, ByVal Bairro As String, ByVal Endereco As String, ByVal Numero As String, ByVal Complemento As String, ByVal CEP As String, ByVal Nome As String, ByVal CPF As String, ByVal DDD As String, ByVal Fone As String, ByVal Registros As Integer, ByVal Higienizar As Boolean, ByVal Bases As String)
            Me.BuscaAutXmlAsync(UF, Cidade, Bairro, Endereco, Numero, Complemento, CEP, Nome, CPF, DDD, Fone, Registros, Higienizar, Bases, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub BuscaAutXmlAsync(ByVal UF As String, ByVal Cidade As String, ByVal Bairro As String, ByVal Endereco As String, ByVal Numero As String, ByVal Complemento As String, ByVal CEP As String, ByVal Nome As String, ByVal CPF As String, ByVal DDD As String, ByVal Fone As String, ByVal Registros As Integer, ByVal Higienizar As Boolean, ByVal Bases As String, ByVal userState As Object)
            If (Me.BuscaAutXmlOperationCompleted Is Nothing) Then
                Me.BuscaAutXmlOperationCompleted = AddressOf Me.OnBuscaAutXmlOperationCompleted
            End If
            Me.InvokeAsync("BuscaAutXml", New Object() {UF, Cidade, Bairro, Endereco, Numero, Complemento, CEP, Nome, CPF, DDD, Fone, Registros, Higienizar, Bases}, Me.BuscaAutXmlOperationCompleted, userState)
        End Sub
        
        Private Sub OnBuscaAutXmlOperationCompleted(ByVal arg As Object)
            If (Not (Me.BuscaAutXmlCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent BuscaAutXmlCompleted(Me, New BuscaAutXmlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.afinder.com.br/BuscaParentesXml", RequestNamespace:="http://www.afinder.com.br", ResponseNamespace:="http://www.afinder.com.br", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function BuscaParentesXml(ByVal UF As String, ByVal Cidade As String, ByVal Bairro As String, ByVal Nome As String, ByVal Registros As Integer, ByVal Bases As String) As System.Xml.XmlNode
            Dim results() As Object = Me.Invoke("BuscaParentesXml", New Object() {UF, Cidade, Bairro, Nome, Registros, Bases})
            Return CType(results(0),System.Xml.XmlNode)
        End Function
        
        '''<remarks/>
        Public Overloads Sub BuscaParentesXmlAsync(ByVal UF As String, ByVal Cidade As String, ByVal Bairro As String, ByVal Nome As String, ByVal Registros As Integer, ByVal Bases As String)
            Me.BuscaParentesXmlAsync(UF, Cidade, Bairro, Nome, Registros, Bases, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub BuscaParentesXmlAsync(ByVal UF As String, ByVal Cidade As String, ByVal Bairro As String, ByVal Nome As String, ByVal Registros As Integer, ByVal Bases As String, ByVal userState As Object)
            If (Me.BuscaParentesXmlOperationCompleted Is Nothing) Then
                Me.BuscaParentesXmlOperationCompleted = AddressOf Me.OnBuscaParentesXmlOperationCompleted
            End If
            Me.InvokeAsync("BuscaParentesXml", New Object() {UF, Cidade, Bairro, Nome, Registros, Bases}, Me.BuscaParentesXmlOperationCompleted, userState)
        End Sub
        
        Private Sub OnBuscaParentesXmlOperationCompleted(ByVal arg As Object)
            If (Not (Me.BuscaParentesXmlCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent BuscaParentesXmlCompleted(Me, New BuscaParentesXmlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.afinder.com.br/BuscaCEPXml", RequestNamespace:="http://www.afinder.com.br", ResponseNamespace:="http://www.afinder.com.br", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function BuscaCEPXml(ByVal CEP As String) As System.Xml.XmlNode
            Dim results() As Object = Me.Invoke("BuscaCEPXml", New Object() {CEP})
            Return CType(results(0),System.Xml.XmlNode)
        End Function
        
        '''<remarks/>
        Public Overloads Sub BuscaCEPXmlAsync(ByVal CEP As String)
            Me.BuscaCEPXmlAsync(CEP, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub BuscaCEPXmlAsync(ByVal CEP As String, ByVal userState As Object)
            If (Me.BuscaCEPXmlOperationCompleted Is Nothing) Then
                Me.BuscaCEPXmlOperationCompleted = AddressOf Me.OnBuscaCEPXmlOperationCompleted
            End If
            Me.InvokeAsync("BuscaCEPXml", New Object() {CEP}, Me.BuscaCEPXmlOperationCompleted, userState)
        End Sub
        
        Private Sub OnBuscaCEPXmlOperationCompleted(ByVal arg As Object)
            If (Not (Me.BuscaCEPXmlCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent BuscaCEPXmlCompleted(Me, New BuscaCEPXmlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.afinder.com.br/HigienizarXml", RequestNamespace:="http://www.afinder.com.br", ResponseNamespace:="http://www.afinder.com.br", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function HigienizarXml(ByVal UF As String, ByVal Cidade As String, ByVal Bairro As String, ByVal Endereco As String, ByVal Numero As String, ByVal Complemento As String, ByVal CEP As String) As System.Xml.XmlNode
            Dim results() As Object = Me.Invoke("HigienizarXml", New Object() {UF, Cidade, Bairro, Endereco, Numero, Complemento, CEP})
            Return CType(results(0),System.Xml.XmlNode)
        End Function
        
        '''<remarks/>
        Public Overloads Sub HigienizarXmlAsync(ByVal UF As String, ByVal Cidade As String, ByVal Bairro As String, ByVal Endereco As String, ByVal Numero As String, ByVal Complemento As String, ByVal CEP As String)
            Me.HigienizarXmlAsync(UF, Cidade, Bairro, Endereco, Numero, Complemento, CEP, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub HigienizarXmlAsync(ByVal UF As String, ByVal Cidade As String, ByVal Bairro As String, ByVal Endereco As String, ByVal Numero As String, ByVal Complemento As String, ByVal CEP As String, ByVal userState As Object)
            If (Me.HigienizarXmlOperationCompleted Is Nothing) Then
                Me.HigienizarXmlOperationCompleted = AddressOf Me.OnHigienizarXmlOperationCompleted
            End If
            Me.InvokeAsync("HigienizarXml", New Object() {UF, Cidade, Bairro, Endereco, Numero, Complemento, CEP}, Me.HigienizarXmlOperationCompleted, userState)
        End Sub
        
        Private Sub OnHigienizarXmlOperationCompleted(ByVal arg As Object)
            If (Not (Me.HigienizarXmlCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent HigienizarXmlCompleted(Me, New HigienizarXmlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.832"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.afinder.com.br"),  _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.afinder.com.br", IsNullable:=false)>  _
    Partial Public Class AuthHeader
        Inherits System.Web.Services.Protocols.SoapHeader
        
        Private usernameField As String
        
        Private passwordField As String
        
        Private anyAttrField() As System.Xml.XmlAttribute
        
        '''<remarks/>
        Public Property Username() As String
            Get
                Return Me.usernameField
            End Get
            Set
                Me.usernameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Password() As String
            Get
                Return Me.passwordField
            End Get
            Set
                Me.passwordField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAnyAttributeAttribute()>  _
        Public Property AnyAttr() As System.Xml.XmlAttribute()
            Get
                Return Me.anyAttrField
            End Get
            Set
                Me.anyAttrField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")>  _
    Public Delegate Sub BuscaFoneticaXmlCompletedEventHandler(ByVal sender As Object, ByVal e As BuscaFoneticaXmlCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class BuscaFoneticaXmlCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Xml.XmlNode
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Xml.XmlNode)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")>  _
    Public Delegate Sub BuscaXmlCompletedEventHandler(ByVal sender As Object, ByVal e As BuscaXmlCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class BuscaXmlCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Xml.XmlNode
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Xml.XmlNode)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")>  _
    Public Delegate Sub BuscaProximidadesXmlCompletedEventHandler(ByVal sender As Object, ByVal e As BuscaProximidadesXmlCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class BuscaProximidadesXmlCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Xml.XmlNode
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Xml.XmlNode)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")>  _
    Public Delegate Sub BuscaCPFXmlCompletedEventHandler(ByVal sender As Object, ByVal e As BuscaCPFXmlCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class BuscaCPFXmlCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Xml.XmlNode
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Xml.XmlNode)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")>  _
    Public Delegate Sub BuscaAutXmlCompletedEventHandler(ByVal sender As Object, ByVal e As BuscaAutXmlCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class BuscaAutXmlCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Xml.XmlNode
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Xml.XmlNode)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")>  _
    Public Delegate Sub BuscaParentesXmlCompletedEventHandler(ByVal sender As Object, ByVal e As BuscaParentesXmlCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class BuscaParentesXmlCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Xml.XmlNode
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Xml.XmlNode)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")>  _
    Public Delegate Sub BuscaCEPXmlCompletedEventHandler(ByVal sender As Object, ByVal e As BuscaCEPXmlCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class BuscaCEPXmlCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Xml.XmlNode
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Xml.XmlNode)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")>  _
    Public Delegate Sub HigienizarXmlCompletedEventHandler(ByVal sender As Object, ByVal e As HigienizarXmlCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class HigienizarXmlCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Xml.XmlNode
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Xml.XmlNode)
            End Get
        End Property
    End Class
End Namespace
